// Shape router — do not edit this file.
// To switch shapes: change `shape` in brand.js → hot reload switches instantly.
// To customise a shape: edit files in src/templates/<shape>/ (done by /5-build).
import { brand } from './brand.js';
import SearchApp from './templates/search/App.jsx';
import ToolApp from './templates/tool/App.jsx';
import DashboardApp from './templates/dashboard/App.jsx';

const shapes = {
  search: SearchApp,
  tool: ToolApp,
  dashboard: DashboardApp,
};

export default function App() {
  const ActiveShape = shapes[brand.shape] ?? SearchApp;
  return <ActiveShape />;
}
